USE DATABASE INGEST_DB;

-- Latest record per customer from RAW (dedupe within load)
WITH latest_raw AS (
  SELECT
    CUSTOMER_ID,
    FULL_NAME,
    EMAIL,
    CITY,
    INGEST_TS,
    LOAD_ID
  FROM RAW.CUSTOMERS_RAW
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CUSTOMER_ID
    ORDER BY INGEST_TS DESC, ROW_NUMBER_IN_FILE DESC
  ) = 1
)

MERGE INTO CURATED.CUSTOMERS t
USING latest_raw s
  ON t.CUSTOMER_ID = s.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
  FULL_NAME  = s.FULL_NAME,
  EMAIL      = s.EMAIL,
  CITY       = s.CITY,
  UPDATED_TS = CURRENT_TIMESTAMP(),
  LOAD_ID    = s.LOAD_ID
WHEN NOT MATCHED THEN INSERT (
  CUSTOMER_ID, FULL_NAME, EMAIL, CITY, UPDATED_TS, LOAD_ID
) VALUES (
  s.CUSTOMER_ID, s.FULL_NAME, s.EMAIL, s.CITY, CURRENT_TIMESTAMP(), s.LOAD_ID
);

-- Curated row count
SELECT COUNT(*) AS curated_rows FROM CURATED.CUSTOMERS;
