USE DATABASE INGEST_DB;

SET PIPELINE_NAME = 'events_json_ingest';
SET LOAD_ID = UUID_STRING();

INSERT INTO OPS.LOAD_LOG (LOAD_ID, PIPELINE_NAME, SOURCE_STAGE, TARGET_TABLE, START_TS, STATUS)
SELECT $LOAD_ID, $PIPELINE_NAME, 'OPS.STG_INTERNAL', 'RAW.EVENTS_RAW', CURRENT_TIMESTAMP(), 'RUNNING';

COPY INTO RAW.EVENTS_RAW (LOAD_ID, FILE_NAME, INGEST_TS, PAYLOAD)
FROM (
  SELECT
    $LOAD_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP(),
    PARSE_JSON($1)
  FROM @OPS.STG_INTERNAL
)
FILE_FORMAT = (FORMAT_NAME = OPS.FF_JSON)
ON_ERROR = 'CONTINUE';

SET ROWS_LOADED = (
  SELECT COALESCE(SUM(rows_loaded),0)
  FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
);

UPDATE OPS.LOAD_LOG
SET END_TS = CURRENT_TIMESTAMP(),
    STATUS = 'SUCCESS',
    ROWS_LOADED = $ROWS_LOADED
WHERE LOAD_ID = $LOAD_ID;
