USE DATABASE INGEST_DB;

-- RAW table for CSV customer-like data
CREATE OR REPLACE TABLE RAW.CUSTOMERS_RAW (
  LOAD_ID          STRING,
  FILE_NAME        STRING,
  ROW_NUMBER_IN_FILE NUMBER,
  INGEST_TS        TIMESTAMP_NTZ,
  CUSTOMER_ID      STRING,
  FULL_NAME        STRING,
  EMAIL            STRING,
  CITY             STRING
);

-- RAW table for JSON events
CREATE OR REPLACE TABLE RAW.EVENTS_RAW (
  LOAD_ID     STRING,
  FILE_NAME   STRING,
  INGEST_TS   TIMESTAMP_NTZ,
  PAYLOAD     VARIANT
);
