-- Choose a warehouse if needed:
-- USE WAREHOUSE <YOUR_WAREHOUSE>;

CREATE OR REPLACE DATABASE INGEST_DB;
CREATE OR REPLACE SCHEMA INGEST_DB.RAW;
CREATE OR REPLACE SCHEMA INGEST_DB.CURATED;
CREATE OR REPLACE SCHEMA INGEST_DB.OPS;

USE DATABASE INGEST_DB;
